Class {
	#name : #ManifestGolapModels,
	#superclass : #PackageManifest,
	#category : #'Golap-Models'
}

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleGRGuradGuardClauseRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #repulseBetween:weight:and:weight:do: #false)) #'2019-07-19T14:49:50.269318+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBCollectionMessagesToExternalObjectRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #move:to: #false)) #'2019-07-19T14:13:25.72332+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBExcessiveArgumentsRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #repulseBetween:weight:and:weight:do: #false)) #'2019-07-19T14:48:51.856003+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBGuardingClauseRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #repulseBetween:weight:and:weight:do: #false)) #'2019-07-19T14:49:24.249024+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBModifiesCollectionRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#GolapModel #buildTiers #false)) #'2019-06-17T17:43:54.981331+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBToDoCollectRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #vertices: #false)) #'2019-07-19T11:31:07.489199+09:00') )
]

{ #category : #'code-critics' }
ManifestGolapModels class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#Golap #repulseBetween:weight:and:weight:do: #false)) #'2019-07-19T14:48:58.776161+09:00') )
]
